// Bangladesh Administrative Geo Data
// Source: nuhil/bangladesh-geocode (github)

export interface GeoItem {
  id: string;
  name: string;
  bn_name: string;
}

export interface District extends GeoItem {
  division_id: string;
}

export interface Upazila extends GeoItem {
  district_id: string;
}

export interface Union extends GeoItem {
  upazila_id: string;
}

export const divisions: GeoItem[] = [
  { id: "1", name: "Chattogram", bn_name: "চট্টগ্রাম" },
  { id: "2", name: "Rajshahi", bn_name: "রাজশাহী" },
  { id: "3", name: "Khulna", bn_name: "খুলনা" },
  { id: "4", name: "Barisal", bn_name: "বরিশাল" },
  { id: "5", name: "Sylhet", bn_name: "সিলেট" },
  { id: "6", name: "Dhaka", bn_name: "ঢাকা" },
  { id: "7", name: "Rangpur", bn_name: "রংপুর" },
  { id: "8", name: "Mymensingh", bn_name: "ময়মনসিংহ" },
];

export const districts: District[] = [
  // Chattogram (1)
  { id: "1", division_id: "1", name: "Comilla", bn_name: "কুমিল্লা" },
  { id: "2", division_id: "1", name: "Feni", bn_name: "ফেনী" },
  { id: "3", division_id: "1", name: "Brahmanbaria", bn_name: "ব্রাহ্মণবাড়িয়া" },
  { id: "4", division_id: "1", name: "Rangamati", bn_name: "রাঙ্গামাটি" },
  { id: "5", division_id: "1", name: "Noakhali", bn_name: "নোয়াখালী" },
  { id: "6", division_id: "1", name: "Chandpur", bn_name: "চাঁদপুর" },
  { id: "7", division_id: "1", name: "Lakshmipur", bn_name: "লক্ষ্মীপুর" },
  { id: "8", division_id: "1", name: "Chattogram", bn_name: "চট্টগ্রাম" },
  { id: "9", division_id: "1", name: "Coxsbazar", bn_name: "কক্সবাজার" },
  { id: "10", division_id: "1", name: "Khagrachhari", bn_name: "খাগড়াছড়ি" },
  { id: "11", division_id: "1", name: "Bandarban", bn_name: "বান্দরবান" },
  // Rajshahi (2)
  { id: "12", division_id: "2", name: "Sirajganj", bn_name: "সিরাজগঞ্জ" },
  { id: "13", division_id: "2", name: "Pabna", bn_name: "পাবনা" },
  { id: "14", division_id: "2", name: "Bogura", bn_name: "বগুড়া" },
  { id: "15", division_id: "2", name: "Rajshahi", bn_name: "রাজশাহী" },
  { id: "16", division_id: "2", name: "Natore", bn_name: "নাটোর" },
  { id: "17", division_id: "2", name: "Joypurhat", bn_name: "জয়পুরহাট" },
  { id: "18", division_id: "2", name: "Chapainawabganj", bn_name: "চাঁপাইনবাবগঞ্জ" },
  { id: "19", division_id: "2", name: "Naogaon", bn_name: "নওগাঁ" },
  // Khulna (3)
  { id: "20", division_id: "3", name: "Jessore", bn_name: "যশোর" },
  { id: "21", division_id: "3", name: "Satkhira", bn_name: "সাতক্ষীরা" },
  { id: "22", division_id: "3", name: "Meherpur", bn_name: "মেহেরপুর" },
  { id: "23", division_id: "3", name: "Narail", bn_name: "নড়াইল" },
  { id: "24", division_id: "3", name: "Chuadanga", bn_name: "চুয়াডাঙ্গা" },
  { id: "25", division_id: "3", name: "Kushtia", bn_name: "কুষ্টিয়া" },
  { id: "26", division_id: "3", name: "Magura", bn_name: "মাগুরা" },
  { id: "27", division_id: "3", name: "Khulna", bn_name: "খুলনা" },
  { id: "28", division_id: "3", name: "Bagerhat", bn_name: "বাগেরহাট" },
  { id: "29", division_id: "3", name: "Jhenaidah", bn_name: "ঝিনাইদহ" },
  // Barisal (4)
  { id: "30", division_id: "4", name: "Jhalokati", bn_name: "ঝালকাঠি" },
  { id: "31", division_id: "4", name: "Patuakhali", bn_name: "পটুয়াখালী" },
  { id: "32", division_id: "4", name: "Pirojpur", bn_name: "পিরোজপুর" },
  { id: "33", division_id: "4", name: "Barisal", bn_name: "বরিশাল" },
  { id: "34", division_id: "4", name: "Bhola", bn_name: "ভোলা" },
  { id: "35", division_id: "4", name: "Barguna", bn_name: "বরগুনা" },
  // Sylhet (5)
  { id: "36", division_id: "5", name: "Sylhet", bn_name: "সিলেট" },
  { id: "37", division_id: "5", name: "Moulvibazar", bn_name: "মৌলভীবাজার" },
  { id: "38", division_id: "5", name: "Habiganj", bn_name: "হবিগঞ্জ" },
  { id: "39", division_id: "5", name: "Sunamganj", bn_name: "সুনামগঞ্জ" },
  // Dhaka (6)
  { id: "40", division_id: "6", name: "Narsingdi", bn_name: "নরসিংদী" },
  { id: "41", division_id: "6", name: "Gazipur", bn_name: "গাজীপুর" },
  { id: "42", division_id: "6", name: "Shariatpur", bn_name: "শরীয়তপুর" },
  { id: "43", division_id: "6", name: "Narayanganj", bn_name: "নারায়ণগঞ্জ" },
  { id: "44", division_id: "6", name: "Tangail", bn_name: "টাঙ্গাইল" },
  { id: "45", division_id: "6", name: "Kishoreganj", bn_name: "কিশোরগঞ্জ" },
  { id: "46", division_id: "6", name: "Manikganj", bn_name: "মানিকগঞ্জ" },
  { id: "47", division_id: "6", name: "Dhaka", bn_name: "ঢাকা" },
  { id: "48", division_id: "6", name: "Munshiganj", bn_name: "মুন্সীগঞ্জ" },
  { id: "49", division_id: "6", name: "Rajbari", bn_name: "রাজবাড়ী" },
  { id: "50", division_id: "6", name: "Madaripur", bn_name: "মাদারীপুর" },
  { id: "51", division_id: "6", name: "Gopalganj", bn_name: "গোপালগঞ্জ" },
  { id: "52", division_id: "6", name: "Faridpur", bn_name: "ফরিদপুর" },
  // Rangpur (7)
  { id: "53", division_id: "7", name: "Panchagarh", bn_name: "পঞ্চগড়" },
  { id: "54", division_id: "7", name: "Dinajpur", bn_name: "দিনাজপুর" },
  { id: "55", division_id: "7", name: "Lalmonirhat", bn_name: "লালমনিরহাট" },
  { id: "56", division_id: "7", name: "Nilphamari", bn_name: "নীলফামারী" },
  { id: "57", division_id: "7", name: "Gaibandha", bn_name: "গাইবান্ধা" },
  { id: "58", division_id: "7", name: "Thakurgaon", bn_name: "ঠাকুরগাঁও" },
  { id: "59", division_id: "7", name: "Rangpur", bn_name: "রংপুর" },
  { id: "60", division_id: "7", name: "Kurigram", bn_name: "কুড়িগ্রাম" },
  // Mymensingh (8)
  { id: "61", division_id: "8", name: "Sherpur", bn_name: "শেরপুর" },
  { id: "62", division_id: "8", name: "Mymensingh", bn_name: "ময়মনসিংহ" },
  { id: "63", division_id: "8", name: "Jamalpur", bn_name: "জামালপুর" },
  { id: "64", division_id: "8", name: "Netrokona", bn_name: "নেত্রকোণা" },
];

export const upazilas: Upazila[] = [
  // Comilla (1)
  { id: "1", district_id: "1", name: "Debidwar", bn_name: "দেবিদ্বার" },
  { id: "2", district_id: "1", name: "Barura", bn_name: "বরুড়া" },
  { id: "3", district_id: "1", name: "Brahmanpara", bn_name: "ব্রাহ্মণপাড়া" },
  { id: "4", district_id: "1", name: "Chandina", bn_name: "চান্দিনা" },
  { id: "5", district_id: "1", name: "Chauddagram", bn_name: "চৌদ্দগ্রাম" },
  { id: "6", district_id: "1", name: "Daudkandi", bn_name: "দাউদকান্দি" },
  { id: "7", district_id: "1", name: "Homna", bn_name: "হোমনা" },
  { id: "8", district_id: "1", name: "Laksam", bn_name: "লাকসাম" },
  { id: "9", district_id: "1", name: "Muradnagar", bn_name: "মুরাদনগর" },
  { id: "10", district_id: "1", name: "Nangalkot", bn_name: "নাঙ্গলকোট" },
  { id: "11", district_id: "1", name: "Comilla Sadar", bn_name: "কুমিল্লা সদর" },
  { id: "12", district_id: "1", name: "Meghna", bn_name: "মেঘনা" },
  { id: "13", district_id: "1", name: "Monohargonj", bn_name: "মনোহরগঞ্জ" },
  { id: "14", district_id: "1", name: "Sadar South", bn_name: "সদর দক্ষিণ" },
  { id: "15", district_id: "1", name: "Titas", bn_name: "তিতাস" },
  { id: "16", district_id: "1", name: "Burichang", bn_name: "বুড়িচং" },
  { id: "17", district_id: "1", name: "Lalmai", bn_name: "লালমাই" },
  // Feni (2)
  { id: "18", district_id: "2", name: "Chhagalnaiya", bn_name: "ছাগলনাইয়া" },
  { id: "19", district_id: "2", name: "Feni Sadar", bn_name: "ফেনী সদর" },
  { id: "20", district_id: "2", name: "Sonagazi", bn_name: "সোনাগাজী" },
  { id: "21", district_id: "2", name: "Fulgazi", bn_name: "ফুলগাজী" },
  { id: "22", district_id: "2", name: "Parshuram", bn_name: "পরশুরাম" },
  { id: "23", district_id: "2", name: "Daganbhuiyan", bn_name: "দাগনভূঞা" },
  // Brahmanbaria (3)
  { id: "24", district_id: "3", name: "Brahmanbaria Sadar", bn_name: "ব্রাহ্মণবাড়িয়া সদর" },
  { id: "25", district_id: "3", name: "Kasba", bn_name: "কসবা" },
  { id: "26", district_id: "3", name: "Nasirnagar", bn_name: "নাসিরনগর" },
  { id: "27", district_id: "3", name: "Sarail", bn_name: "সরাইল" },
  { id: "28", district_id: "3", name: "Ashuganj", bn_name: "আশুগঞ্জ" },
  { id: "29", district_id: "3", name: "Akhaura", bn_name: "আখাউড়া" },
  { id: "30", district_id: "3", name: "Nabinagar", bn_name: "নবীনগর" },
  { id: "31", district_id: "3", name: "Bancharampur", bn_name: "বাঞ্ছারামপুর" },
  { id: "32", district_id: "3", name: "Bijoynagar", bn_name: "বিজয়নগর" },
  // Rangamati (4)
  { id: "33", district_id: "4", name: "Rangamati Sadar", bn_name: "রাঙ্গামাটি সদর" },
  { id: "34", district_id: "4", name: "Kaptai", bn_name: "কাপ্তাই" },
  { id: "35", district_id: "4", name: "Kawkhali", bn_name: "কাউখালী" },
  { id: "36", district_id: "4", name: "Baghaichari", bn_name: "বাঘাইছড়ি" },
  { id: "37", district_id: "4", name: "Barkal", bn_name: "বরকল" },
  { id: "38", district_id: "4", name: "Langadu", bn_name: "লংগদু" },
  { id: "39", district_id: "4", name: "Rajasthali", bn_name: "রাজস্থলী" },
  { id: "40", district_id: "4", name: "Belaichari", bn_name: "বিলাইছড়ি" },
  { id: "41", district_id: "4", name: "Juraichari", bn_name: "জুরাছড়ি" },
  { id: "42", district_id: "4", name: "Naniarchar", bn_name: "নানিয়ারচর" },
  // Noakhali (5)
  { id: "43", district_id: "5", name: "Noakhali Sadar", bn_name: "নোয়াখালী সদর" },
  { id: "44", district_id: "5", name: "Companiganj", bn_name: "কোম্পানীগঞ্জ" },
  { id: "45", district_id: "5", name: "Begumganj", bn_name: "বেগমগঞ্জ" },
  { id: "46", district_id: "5", name: "Hatia", bn_name: "হাতিয়া" },
  { id: "47", district_id: "5", name: "Subarnachar", bn_name: "সুবর্ণচর" },
  { id: "48", district_id: "5", name: "Kabirhat", bn_name: "কবিরহাট" },
  { id: "49", district_id: "5", name: "Senbug", bn_name: "সেনবাগ" },
  { id: "50", district_id: "5", name: "Chatkhil", bn_name: "চাটখিল" },
  { id: "51", district_id: "5", name: "Sonaimori", bn_name: "সোনাইমুড়ী" },
  // Chandpur (6)
  { id: "52", district_id: "6", name: "Haimchar", bn_name: "হাইমচর" },
  { id: "53", district_id: "6", name: "Kachua", bn_name: "কচুয়া" },
  { id: "54", district_id: "6", name: "Shahrasti", bn_name: "শাহরাস্তি" },
  { id: "55", district_id: "6", name: "Chandpur Sadar", bn_name: "চাঁদপুর সদর" },
  { id: "56", district_id: "6", name: "Matlab South", bn_name: "মতলব দক্ষিণ" },
  { id: "57", district_id: "6", name: "Hajiganj", bn_name: "হাজীগঞ্জ" },
  { id: "58", district_id: "6", name: "Matlab North", bn_name: "মতলব উত্তর" },
  { id: "59", district_id: "6", name: "Faridgonj", bn_name: "ফরিদগঞ্জ" },
  // Lakshmipur (7)
  { id: "60", district_id: "7", name: "Lakshmipur Sadar", bn_name: "লক্ষ্মীপুর সদর" },
  { id: "61", district_id: "7", name: "Kamalnagar", bn_name: "কমলনগর" },
  { id: "62", district_id: "7", name: "Raipur", bn_name: "রায়পুর" },
  { id: "63", district_id: "7", name: "Ramgati", bn_name: "রামগতি" },
  { id: "64", district_id: "7", name: "Ramganj", bn_name: "রামগঞ্জ" },
  // Chattogram (8)
  { id: "65", district_id: "8", name: "Rangunia", bn_name: "রাঙ্গুনিয়া" },
  { id: "66", district_id: "8", name: "Sitakunda", bn_name: "সীতাকুন্ড" },
  { id: "67", district_id: "8", name: "Mirsharai", bn_name: "মীরসরাই" },
  { id: "68", district_id: "8", name: "Patiya", bn_name: "পটিয়া" },
  { id: "69", district_id: "8", name: "Sandwip", bn_name: "সন্দ্বীপ" },
  { id: "70", district_id: "8", name: "Banshkhali", bn_name: "বাঁশখালী" },
  { id: "71", district_id: "8", name: "Boalkhali", bn_name: "বোয়ালখালী" },
  { id: "72", district_id: "8", name: "Anwara", bn_name: "আনোয়ারা" },
  { id: "73", district_id: "8", name: "Chandanaish", bn_name: "চন্দনাইশ" },
  { id: "74", district_id: "8", name: "Satkania", bn_name: "সাতকানিয়া" },
  { id: "75", district_id: "8", name: "Lohagara", bn_name: "লোহাগাড়া" },
  { id: "76", district_id: "8", name: "Hathazari", bn_name: "হাটহাজারী" },
  { id: "77", district_id: "8", name: "Fatikchhari", bn_name: "ফটিকছড়ি" },
  { id: "78", district_id: "8", name: "Raozan", bn_name: "রাউজান" },
  { id: "79", district_id: "8", name: "Karnafuli", bn_name: "কর্ণফুলী" },
  { id: "80", district_id: "8", name: "Chattogram Sadar", bn_name: "চট্টগ্রাম সদর" },
  // Coxsbazar (9)
  { id: "81", district_id: "9", name: "Coxsbazar Sadar", bn_name: "কক্সবাজার সদর" },
  { id: "82", district_id: "9", name: "Chakaria", bn_name: "চকরিয়া" },
  { id: "83", district_id: "9", name: "Kutubdia", bn_name: "কুতুবদিয়া" },
  { id: "84", district_id: "9", name: "Ukhiya", bn_name: "উখিয়া" },
  { id: "85", district_id: "9", name: "Moheshkhali", bn_name: "মহেশখালী" },
  { id: "86", district_id: "9", name: "Pekua", bn_name: "পেকুয়া" },
  { id: "87", district_id: "9", name: "Ramu", bn_name: "রামু" },
  { id: "88", district_id: "9", name: "Teknaf", bn_name: "টেকনাফ" },
  // Khagrachhari (10)
  { id: "89", district_id: "10", name: "Khagrachhari Sadar", bn_name: "খাগড়াছড়ি সদর" },
  { id: "90", district_id: "10", name: "Dighinala", bn_name: "দিঘীনালা" },
  { id: "91", district_id: "10", name: "Panchari", bn_name: "পানছড়ি" },
  { id: "92", district_id: "10", name: "Laxmichhari", bn_name: "লক্ষীছড়ি" },
  { id: "93", district_id: "10", name: "Mohalchari", bn_name: "মহালছড়ি" },
  { id: "94", district_id: "10", name: "Manikchari", bn_name: "মানিকছড়ি" },
  { id: "95", district_id: "10", name: "Ramgarh", bn_name: "রামগড়" },
  { id: "96", district_id: "10", name: "Matichari", bn_name: "মাটিরাঙ্গা" },
  { id: "97", district_id: "10", name: "Guimara", bn_name: "গুইমারা" },
  // Bandarban (11)
  { id: "98", district_id: "11", name: "Bandarban Sadar", bn_name: "বান্দরবান সদর" },
  { id: "99", district_id: "11", name: "Alikadam", bn_name: "আলীকদম" },
  { id: "100", district_id: "11", name: "Naikhangchhari", bn_name: "নাইক্ষ্যংছড়ি" },
  { id: "101", district_id: "11", name: "Rowangchhari", bn_name: "রোয়াংছড়ি" },
  { id: "102", district_id: "11", name: "Lama", bn_name: "লামা" },
  { id: "103", district_id: "11", name: "Ruma", bn_name: "রুমা" },
  { id: "104", district_id: "11", name: "Thanchi", bn_name: "থানচি" },
  // Sirajganj (12)
  { id: "105", district_id: "12", name: "Sirajganj Sadar", bn_name: "সিরাজগঞ্জ সদর" },
  { id: "106", district_id: "12", name: "Belkuchi", bn_name: "বেলকুচি" },
  { id: "107", district_id: "12", name: "Chauhali", bn_name: "চৌহালি" },
  { id: "108", district_id: "12", name: "Kamarkhanda", bn_name: "কামারখন্দ" },
  { id: "109", district_id: "12", name: "Kazipur", bn_name: "কাজীপুর" },
  { id: "110", district_id: "12", name: "Raiganj", bn_name: "রায়গঞ্জ" },
  { id: "111", district_id: "12", name: "Shahjadpur", bn_name: "শাহজাদপুর" },
  { id: "112", district_id: "12", name: "Tarash", bn_name: "তাড়াশ" },
  { id: "113", district_id: "12", name: "Ullahpara", bn_name: "উল্লাপাড়া" },
  // Dhaka (47)
  { id: "200", district_id: "47", name: "Dhamrai", bn_name: "ধামরাই" },
  { id: "201", district_id: "47", name: "Dohar", bn_name: "দোহার" },
  { id: "202", district_id: "47", name: "Keraniganj", bn_name: "কেরানীগঞ্জ" },
  { id: "203", district_id: "47", name: "Nawabganj", bn_name: "নবাবগঞ্জ" },
  { id: "204", district_id: "47", name: "Savar", bn_name: "সাভার" },
  { id: "205", district_id: "47", name: "Dhaka Sadar", bn_name: "ঢাকা সদর" },
  // Narayanganj (43)
  { id: "210", district_id: "43", name: "Araihazar", bn_name: "আড়াইহাজার" },
  { id: "211", district_id: "43", name: "Bandar", bn_name: "বন্দর" },
  { id: "212", district_id: "43", name: "Narayanganj Sadar", bn_name: "নারায়ণগঞ্জ সদর" },
  { id: "213", district_id: "43", name: "Rupganj", bn_name: "রূপগঞ্জ" },
  { id: "214", district_id: "43", name: "Sonargaon", bn_name: "সোনারগাঁও" },
  // Gazipur (41)
  { id: "220", district_id: "41", name: "Gazipur Sadar", bn_name: "গাজীপুর সদর" },
  { id: "221", district_id: "41", name: "Kaliakair", bn_name: "কালিয়াকৈর" },
  { id: "222", district_id: "41", name: "Kaliganj", bn_name: "কালীগঞ্জ" },
  { id: "223", district_id: "41", name: "Kapasia", bn_name: "কাপাসিয়া" },
  { id: "224", district_id: "41", name: "Sreepur", bn_name: "শ্রীপুর" },
  // Sylhet (36)
  { id: "230", district_id: "36", name: "Balaganj", bn_name: "বালাগঞ্জ" },
  { id: "231", district_id: "36", name: "Beanibazar", bn_name: "বিয়ানীবাজার" },
  { id: "232", district_id: "36", name: "Bishwanath", bn_name: "বিশ্বনাথ" },
  { id: "233", district_id: "36", name: "Companiganj", bn_name: "কোম্পানীগঞ্জ" },
  { id: "234", district_id: "36", name: "Dakshin Surma", bn_name: "দক্ষিণ সুরমা" },
  { id: "235", district_id: "36", name: "Fenchuganj", bn_name: "ফেঞ্চুগঞ্জ" },
  { id: "236", district_id: "36", name: "Golapganj", bn_name: "গোলাপগঞ্জ" },
  { id: "237", district_id: "36", name: "Gowainghat", bn_name: "গোয়াইনঘাট" },
  { id: "238", district_id: "36", name: "Jaintiapur", bn_name: "জৈন্তাপুর" },
  { id: "239", district_id: "36", name: "Kanaighat", bn_name: "কানাইঘাট" },
  { id: "240", district_id: "36", name: "Sylhet Sadar", bn_name: "সিলেট সদর" },
  { id: "241", district_id: "36", name: "Zakiganj", bn_name: "জকিগঞ্জ" },
  // Rajshahi (15)
  { id: "250", district_id: "15", name: "Bagha", bn_name: "বাঘা" },
  { id: "251", district_id: "15", name: "Bagmara", bn_name: "বাগমারা" },
  { id: "252", district_id: "15", name: "Charghat", bn_name: "চারঘাট" },
  { id: "253", district_id: "15", name: "Durgapur", bn_name: "দুর্গাপুর" },
  { id: "254", district_id: "15", name: "Godagari", bn_name: "গোদাগাড়ী" },
  { id: "255", district_id: "15", name: "Mohanpur", bn_name: "মোহনপুর" },
  { id: "256", district_id: "15", name: "Paba", bn_name: "পবা" },
  { id: "257", district_id: "15", name: "Puthia", bn_name: "পুঠিয়া" },
  { id: "258", district_id: "15", name: "Tanore", bn_name: "তানোর" },
  // Khulna (27)
  { id: "260", district_id: "27", name: "Batiaghata", bn_name: "বটিয়াঘাটা" },
  { id: "261", district_id: "27", name: "Dacope", bn_name: "দাকোপ" },
  { id: "262", district_id: "27", name: "Dumuria", bn_name: "ডুমুরিয়া" },
  { id: "263", district_id: "27", name: "Dighalia", bn_name: "দিঘলিয়া" },
  { id: "264", district_id: "27", name: "Koyra", bn_name: "কয়রা" },
  { id: "265", district_id: "27", name: "Paikgachha", bn_name: "পাইকগাছা" },
  { id: "266", district_id: "27", name: "Phultala", bn_name: "ফুলতলা" },
  { id: "267", district_id: "27", name: "Rupsa", bn_name: "রূপসা" },
  { id: "268", district_id: "27", name: "Terokhada", bn_name: "তেরখাদা" },
  { id: "269", district_id: "27", name: "Khulna Sadar", bn_name: "খুলনা সদর" },
  // Barisal (33)
  { id: "270", district_id: "33", name: "Agailjhara", bn_name: "আগৈলঝাড়া" },
  { id: "271", district_id: "33", name: "Babuganj", bn_name: "বাবুগঞ্জ" },
  { id: "272", district_id: "33", name: "Bakerganj", bn_name: "বাকেরগঞ্জ" },
  { id: "273", district_id: "33", name: "Banaripara", bn_name: "বানারীপাড়া" },
  { id: "274", district_id: "33", name: "Gaurnadi", bn_name: "গৌরনদী" },
  { id: "275", district_id: "33", name: "Hizla", bn_name: "হিজলা" },
  { id: "276", district_id: "33", name: "Barisal Sadar", bn_name: "বরিশাল সদর" },
  { id: "277", district_id: "33", name: "Mehendiganj", bn_name: "মেহেন্দিগঞ্জ" },
  { id: "278", district_id: "33", name: "Muladi", bn_name: "মুলাদী" },
  { id: "279", district_id: "33", name: "Wazirpur", bn_name: "উজিরপুর" },
  // Rangpur (59)
  { id: "280", district_id: "59", name: "Badarganj", bn_name: "বদরগঞ্জ" },
  { id: "281", district_id: "59", name: "Gangachara", bn_name: "গঙ্গাচড়া" },
  { id: "282", district_id: "59", name: "Kaunia", bn_name: "কাউনিয়া" },
  { id: "283", district_id: "59", name: "Rangpur Sadar", bn_name: "রংপুর সদর" },
  { id: "284", district_id: "59", name: "Mithapukur", bn_name: "মিঠাপুকুর" },
  { id: "285", district_id: "59", name: "Pirgachha", bn_name: "পীরগাছা" },
  { id: "286", district_id: "59", name: "Pirganj", bn_name: "পীরগঞ্জ" },
  { id: "287", district_id: "59", name: "Taraganj", bn_name: "তারাগঞ্জ" },
  // Mymensingh (62)
  { id: "290", district_id: "62", name: "Bhaluka", bn_name: "ভালুকা" },
  { id: "291", district_id: "62", name: "Dhobaura", bn_name: "ধোবাউড়া" },
  { id: "292", district_id: "62", name: "Fulbaria", bn_name: "ফুলবাড়িয়া" },
  { id: "293", district_id: "62", name: "Gaffargaon", bn_name: "গফরগাঁও" },
  { id: "294", district_id: "62", name: "Gauripur", bn_name: "গৌরীপুর" },
  { id: "295", district_id: "62", name: "Haluaghat", bn_name: "হালুয়াঘাট" },
  { id: "296", district_id: "62", name: "Ishwarganj", bn_name: "ঈশ্বরগঞ্জ" },
  { id: "297", district_id: "62", name: "Mymensingh Sadar", bn_name: "ময়মনসিংহ সদর" },
  { id: "298", district_id: "62", name: "Muktagachha", bn_name: "মুক্তাগাছা" },
  { id: "299", district_id: "62", name: "Nandail", bn_name: "নান্দাইল" },
  { id: "300", district_id: "62", name: "Phulpur", bn_name: "ফুলপুর" },
  { id: "301", district_id: "62", name: "Trishal", bn_name: "ত্রিশাল" },
  { id: "302", district_id: "62", name: "Tarakanda", bn_name: "তারাকান্দা" },
  // Tangail (44)
  { id: "310", district_id: "44", name: "Basail", bn_name: "বাসাইল" },
  { id: "311", district_id: "44", name: "Bhuapur", bn_name: "ভূয়াপুর" },
  { id: "312", district_id: "44", name: "Delduar", bn_name: "দেলদুয়ার" },
  { id: "313", district_id: "44", name: "Ghatail", bn_name: "ঘাটাইল" },
  { id: "314", district_id: "44", name: "Gopalpur", bn_name: "গোপালপুর" },
  { id: "315", district_id: "44", name: "Kalihati", bn_name: "কালিহাতী" },
  { id: "316", district_id: "44", name: "Madhupur", bn_name: "মধুপুর" },
  { id: "317", district_id: "44", name: "Mirzapur", bn_name: "মির্জাপুর" },
  { id: "318", district_id: "44", name: "Nagarpur", bn_name: "নাগরপুর" },
  { id: "319", district_id: "44", name: "Sakhipur", bn_name: "সখিপুর" },
  { id: "320", district_id: "44", name: "Tangail Sadar", bn_name: "টাঙ্গাইল সদর" },
  { id: "321", district_id: "44", name: "Dhanbari", bn_name: "ধনবাড়ী" },
  // Kishoreganj (45)
  { id: "330", district_id: "45", name: "Austagram", bn_name: "অষ্টগ্রাম" },
  { id: "331", district_id: "45", name: "Bajitpur", bn_name: "বাজিতপুর" },
  { id: "332", district_id: "45", name: "Bhairab", bn_name: "ভৈরব" },
  { id: "333", district_id: "45", name: "Hossainpur", bn_name: "হোসেনপুর" },
  { id: "334", district_id: "45", name: "Itna", bn_name: "ইটনা" },
  { id: "335", district_id: "45", name: "Karimganj", bn_name: "করিমগঞ্জ" },
  { id: "336", district_id: "45", name: "Katiadi", bn_name: "কটিয়াদী" },
  { id: "337", district_id: "45", name: "Kishoreganj Sadar", bn_name: "কিশোরগঞ্জ সদর" },
  { id: "338", district_id: "45", name: "Kuliarchar", bn_name: "কুলিয়ারচর" },
  { id: "339", district_id: "45", name: "Mithamain", bn_name: "মিঠামইন" },
  { id: "340", district_id: "45", name: "Nikli", bn_name: "নিকলী" },
  { id: "341", district_id: "45", name: "Pakundia", bn_name: "পাকুন্দিয়া" },
  { id: "342", district_id: "45", name: "Tarail", bn_name: "তাড়াইল" },
  // Bogura (14)
  { id: "350", district_id: "14", name: "Adamdighi", bn_name: "আদমদিঘি" },
  { id: "351", district_id: "14", name: "Bogura Sadar", bn_name: "বগুড়া সদর" },
  { id: "352", district_id: "14", name: "Dhunot", bn_name: "ধুনট" },
  { id: "353", district_id: "14", name: "Dupchanchia", bn_name: "দুপচাঁচিয়া" },
  { id: "354", district_id: "14", name: "Gabtali", bn_name: "গাবতলী" },
  { id: "355", district_id: "14", name: "Kahaloo", bn_name: "কাহালু" },
  { id: "356", district_id: "14", name: "Nandigram", bn_name: "নন্দীগ্রাম" },
  { id: "357", district_id: "14", name: "Sariakandi", bn_name: "সারিয়াকান্দি" },
  { id: "358", district_id: "14", name: "Shajahanpur", bn_name: "শাজাহানপুর" },
  { id: "359", district_id: "14", name: "Sherpur", bn_name: "শেরপুর" },
  { id: "360", district_id: "14", name: "Shibganj", bn_name: "শিবগঞ্জ" },
  { id: "361", district_id: "14", name: "Sonatola", bn_name: "সোনাতলা" },
  // Jessore (20)
  { id: "370", district_id: "20", name: "Abhaynagar", bn_name: "অভয়নগর" },
  { id: "371", district_id: "20", name: "Bagherpara", bn_name: "বাঘারপাড়া" },
  { id: "372", district_id: "20", name: "Chaugachha", bn_name: "চৌগাছা" },
  { id: "373", district_id: "20", name: "Jhikargachha", bn_name: "ঝিকরগাছা" },
  { id: "374", district_id: "20", name: "Keshabpur", bn_name: "কেশবপুর" },
  { id: "375", district_id: "20", name: "Jessore Sadar", bn_name: "যশোর সদর" },
  { id: "376", district_id: "20", name: "Manirampur", bn_name: "মনিরামপুর" },
  { id: "377", district_id: "20", name: "Sharsha", bn_name: "শার্শা" },
  // Dinajpur (54)
  { id: "380", district_id: "54", name: "Birampur", bn_name: "বিরামপুর" },
  { id: "381", district_id: "54", name: "Birganj", bn_name: "বীরগঞ্জ" },
  { id: "382", district_id: "54", name: "Biral", bn_name: "বিরল" },
  { id: "383", district_id: "54", name: "Bochaganj", bn_name: "বোচাগঞ্জ" },
  { id: "384", district_id: "54", name: "Chirirbandar", bn_name: "চিরিরবন্দর" },
  { id: "385", district_id: "54", name: "Phulbari", bn_name: "ফুলবাড়ী" },
  { id: "386", district_id: "54", name: "Ghoraghat", bn_name: "ঘোড়াঘাট" },
  { id: "387", district_id: "54", name: "Hakimpur", bn_name: "হাকিমপুর" },
  { id: "388", district_id: "54", name: "Kaharole", bn_name: "কাহারোল" },
  { id: "389", district_id: "54", name: "Khansama", bn_name: "খানসামা" },
  { id: "390", district_id: "54", name: "Dinajpur Sadar", bn_name: "দিনাজপুর সদর" },
  { id: "391", district_id: "54", name: "Nawabganj", bn_name: "নবাবগঞ্জ" },
  { id: "392", district_id: "54", name: "Parbatipur", bn_name: "পার্বতীপুর" },
  // Narsingdi (40)
  { id: "400", district_id: "40", name: "Belabo", bn_name: "বেলাবো" },
  { id: "401", district_id: "40", name: "Monohardi", bn_name: "মনোহরদী" },
  { id: "402", district_id: "40", name: "Narsingdi Sadar", bn_name: "নরসিংদী সদর" },
  { id: "403", district_id: "40", name: "Palash", bn_name: "পলাশ" },
  { id: "404", district_id: "40", name: "Raipura", bn_name: "রায়পুরা" },
  { id: "405", district_id: "40", name: "Shibpur", bn_name: "শিবপুর" },
  // Habiganj (38)
  { id: "410", district_id: "38", name: "Ajmiriganj", bn_name: "আজমিরীগঞ্জ" },
  { id: "411", district_id: "38", name: "Baniachong", bn_name: "বানিয়াচং" },
  { id: "412", district_id: "38", name: "Bahubal", bn_name: "বাহুবল" },
  { id: "413", district_id: "38", name: "Chunarughat", bn_name: "চুনারুঘাট" },
  { id: "414", district_id: "38", name: "Habiganj Sadar", bn_name: "হবিগঞ্জ সদর" },
  { id: "415", district_id: "38", name: "Lakhai", bn_name: "লাখাই" },
  { id: "416", district_id: "38", name: "Madhabpur", bn_name: "মাধবপুর" },
  { id: "417", district_id: "38", name: "Nabiganj", bn_name: "নবীগঞ্জ" },
  // Moulvibazar (37)
  { id: "420", district_id: "37", name: "Barlekha", bn_name: "বড়লেখা" },
  { id: "421", district_id: "37", name: "Juri", bn_name: "জুড়ী" },
  { id: "422", district_id: "37", name: "Kamalganj", bn_name: "কমলগঞ্জ" },
  { id: "423", district_id: "37", name: "Kulaura", bn_name: "কুলাউড়া" },
  { id: "424", district_id: "37", name: "Moulvibazar Sadar", bn_name: "মৌলভীবাজার সদর" },
  { id: "425", district_id: "37", name: "Rajnagar", bn_name: "রাজনগর" },
  { id: "426", district_id: "37", name: "Sreemangal", bn_name: "শ্রীমঙ্গল" },
  // Sunamganj (39)
  { id: "430", district_id: "39", name: "Bishwamvarpur", bn_name: "বিশ্বম্ভরপুর" },
  { id: "431", district_id: "39", name: "Chhatak", bn_name: "ছাতক" },
  { id: "432", district_id: "39", name: "Derai", bn_name: "দিরাই" },
  { id: "433", district_id: "39", name: "Dharampasha", bn_name: "ধর্মপাশা" },
  { id: "434", district_id: "39", name: "Dowarabazar", bn_name: "দোয়ারাবাজার" },
  { id: "435", district_id: "39", name: "Jagannathpur", bn_name: "জগন্নাথপুর" },
  { id: "436", district_id: "39", name: "Jamalganj", bn_name: "জামালগঞ্জ" },
  { id: "437", district_id: "39", name: "Sulla", bn_name: "শাল্লা" },
  { id: "438", district_id: "39", name: "Sunamganj Sadar", bn_name: "সুনামগঞ্জ সদর" },
  { id: "439", district_id: "39", name: "Tahirpur", bn_name: "তাহিরপুর" },
  // Faridpur (52)
  { id: "440", district_id: "52", name: "Alfadanga", bn_name: "আলফাডাঙ্গা" },
  { id: "441", district_id: "52", name: "Bhanga", bn_name: "ভাঙ্গা" },
  { id: "442", district_id: "52", name: "Boalmari", bn_name: "বোয়ালমারী" },
  { id: "443", district_id: "52", name: "Char Bhadrasan", bn_name: "চরভদ্রাসন" },
  { id: "444", district_id: "52", name: "Faridpur Sadar", bn_name: "ফরিদপুর সদর" },
  { id: "445", district_id: "52", name: "Madhukhali", bn_name: "মধুখালী" },
  { id: "446", district_id: "52", name: "Nagarkanda", bn_name: "নগরকান্দা" },
  { id: "447", district_id: "52", name: "Sadarpur", bn_name: "সদরপুর" },
  { id: "448", district_id: "52", name: "Saltha", bn_name: "সালথা" },
  // Gopalganj (51)
  { id: "450", district_id: "51", name: "Gopalganj Sadar", bn_name: "গোপালগঞ্জ সদর" },
  { id: "451", district_id: "51", name: "Kashiani", bn_name: "কাশিয়ানী" },
  { id: "452", district_id: "51", name: "Kotalipara", bn_name: "কোটালীপাড়া" },
  { id: "453", district_id: "51", name: "Muksudpur", bn_name: "মুকসুদপুর" },
  { id: "454", district_id: "51", name: "Tungipara", bn_name: "টুঙ্গিপাড়া" },
  // Kushtia (25)
  { id: "460", district_id: "25", name: "Bheramara", bn_name: "ভেড়ামারা" },
  { id: "461", district_id: "25", name: "Daulatpur", bn_name: "দৌলতপুর" },
  { id: "462", district_id: "25", name: "Khoksa", bn_name: "খোকসা" },
  { id: "463", district_id: "25", name: "Kumarkhali", bn_name: "কুমারখালী" },
  { id: "464", district_id: "25", name: "Kushtia Sadar", bn_name: "কুষ্টিয়া সদর" },
  { id: "465", district_id: "25", name: "Mirpur", bn_name: "মিরপুর" },
  // Patuakhali (31)
  { id: "470", district_id: "31", name: "Bauphal", bn_name: "বাউফল" },
  { id: "471", district_id: "31", name: "Dashmina", bn_name: "দশমিনা" },
  { id: "472", district_id: "31", name: "Dumki", bn_name: "দুমকি" },
  { id: "473", district_id: "31", name: "Galachipa", bn_name: "গলাচিপা" },
  { id: "474", district_id: "31", name: "Kalapara", bn_name: "কলাপাড়া" },
  { id: "475", district_id: "31", name: "Mirzaganj", bn_name: "মির্জাগঞ্জ" },
  { id: "476", district_id: "31", name: "Patuakhali Sadar", bn_name: "পটুয়াখালী সদর" },
  { id: "477", district_id: "31", name: "Rangabali", bn_name: "রাঙ্গাবালী" },
  // Panchagarh (53)
  { id: "480", district_id: "53", name: "Atwari", bn_name: "আটোয়ারী" },
  { id: "481", district_id: "53", name: "Boda", bn_name: "বোদা" },
  { id: "482", district_id: "53", name: "Debiganj", bn_name: "দেবীগঞ্জ" },
  { id: "483", district_id: "53", name: "Panchagarh Sadar", bn_name: "পঞ্চগড় সদর" },
  { id: "484", district_id: "53", name: "Tetulia", bn_name: "তেঁতুলিয়া" },
  // Sherpur (61)
  { id: "490", district_id: "61", name: "Jhenaigati", bn_name: "ঝিনাইগাতী" },
  { id: "491", district_id: "61", name: "Nakla", bn_name: "নকলা" },
  { id: "492", district_id: "61", name: "Nalitabari", bn_name: "নালিতাবাড়ী" },
  { id: "493", district_id: "61", name: "Sherpur Sadar", bn_name: "শেরপুর সদর" },
  { id: "494", district_id: "61", name: "Sribordi", bn_name: "শ্রীবরদী" },
  // Netrokona (64)
  { id: "500", district_id: "64", name: "Atpara", bn_name: "আটপাড়া" },
  { id: "501", district_id: "64", name: "Barhatta", bn_name: "বারহাট্টা" },
  { id: "502", district_id: "64", name: "Durgapur", bn_name: "দুর্গাপুর" },
  { id: "503", district_id: "64", name: "Kendua", bn_name: "কেন্দুয়া" },
  { id: "504", district_id: "64", name: "Kalmakanda", bn_name: "কলমাকান্দা" },
  { id: "505", district_id: "64", name: "Madan", bn_name: "মদন" },
  { id: "506", district_id: "64", name: "Mohanganj", bn_name: "মোহনগঞ্জ" },
  { id: "507", district_id: "64", name: "Netrokona Sadar", bn_name: "নেত্রকোণা সদর" },
  { id: "508", district_id: "64", name: "Purbadhala", bn_name: "পূর্বধলা" },
  { id: "509", district_id: "64", name: "Khaliajuri", bn_name: "খালিয়াজুরী" },
  // Jamalpur (63)
  { id: "510", district_id: "63", name: "Bakshiganj", bn_name: "বকশীগঞ্জ" },
  { id: "511", district_id: "63", name: "Dewanganj", bn_name: "দেওয়ানগঞ্জ" },
  { id: "512", district_id: "63", name: "Islampur", bn_name: "ইসলামপুর" },
  { id: "513", district_id: "63", name: "Jamalpur Sadar", bn_name: "জামালপুর সদর" },
  { id: "514", district_id: "63", name: "Madarganj", bn_name: "মাদারগঞ্জ" },
  { id: "515", district_id: "63", name: "Melandaha", bn_name: "মেলান্দহ" },
  { id: "516", district_id: "63", name: "Sarishabari", bn_name: "সরিষাবাড়ী" },
];

// Helper functions
export function getDistrictsByDivision(divisionId: string): District[] {
  return districts.filter(d => d.division_id === divisionId);
}

export function getUpazilasByDistrict(districtId: string): Upazila[] {
  return upazilas.filter(u => u.district_id === districtId);
}
