import { z } from 'zod';

const addressSchema = (isBn: boolean) => z.object({
  division: z.string().optional(),
  district: z.string().min(1, { message: isBn ? "জেলা নির্বাচন করুন" : "Select district" }),
  upazila: z.string().min(1, { message: isBn ? "উপজেলা নির্বাচন করুন" : "Select upazila" }),
  union: z.string().min(1, { message: isBn ? "ইউনিয়ন/পৌরসভা লিখুন" : "Enter union/municipality" }),
  village: z.string().min(1, { message: isBn ? "গ্রাম/মহল্লার নাম লিখুন" : "Enter village/area" }),
  postCode: z.string().min(4, { message: isBn ? "সঠিক পোস্ট কোড দিন" : "Enter valid post code" }),
  houseNo: z.string().optional(),
  flatNo: z.string().optional(),
  holdingNo: z.string().optional(),
  roadNo: z.string().optional(),
  ownership: z.string().optional(),
  rentAmount: z.string().optional(),
  stayDuration: z.string().optional(),
});

export const getLoanSchema = (isBn: boolean) => z.object({
  // Step 3
  fullName: z.string().min(3, { message: isBn ? "সঠিক নাম দিন" : "Enter a valid name" }),
  fatherName: z.string().min(3, { message: isBn ? "পিতার নাম দিন" : "Enter father's name" }),
  motherName: z.string().min(3, { message: isBn ? "মাতার নাম দিন" : "Enter mother's name" }),
  dob: z.string().min(1, { message: isBn ? "জন্ম তারিখ দিন" : "Select date of birth" }),
  gender: z.string().min(1, { message: isBn ? "লিঙ্গ নির্বাচন করুন" : "Select gender" }),
  mobile: z.string().regex(/^(01)[3-9][0-9]{8}$/, { message: isBn ? "সঠিক মোবাইল নাম্বার দিন (১১ ডিজিট)" : "Enter valid mobile number" }),
  whatsapp: z.string().optional().or(z.literal('')),
  email: z.string().email({ message: isBn ? "সঠিক ইমেইল দিন" : "Enter a valid email" }).optional().or(z.literal('')),
  currentAddress: addressSchema(isBn),
  permanentAddress: addressSchema(isBn),
  nidNumber: z.string().min(10, { message: isBn ? "সঠিক NID নাম্বার দিন (অন্তত ১০ ডিজিট)" : "Enter valid NID (min 10 digits)" }),
  
  // New Personal Info additions
  eTin: z.string().optional(),
  bloodGroup: z.string().optional(),
  maritalStatus: z.string().optional(),
  spouseProfession: z.string().optional(),
  spouseIncome: z.string().optional(),

  // Step 4 - Using min(1) so they fail if empty, but we'll only trigger them conditionally
  companyName: z.string().min(1, { message: isBn ? "কোম্পানির নাম দিন" : "Enter company name" }).optional(),
  designation: z.string().min(1, { message: isBn ? "পদবী দিন" : "Enter designation" }).optional(),
  workDuration: z.string().min(1, { message: isBn ? "কাজের মেয়াদ দিন" : "Enter work duration" }).optional(),
  monthlyIncome: z.string().min(1, { message: isBn ? "মাসিক আয় দিন" : "Enter monthly income" }).optional(),
  jobAddress: z.string().min(1, { message: isBn ? "ঠিকানা দিন" : "Enter address" }).optional(),
  
  // New Personal Loan specific professional & financial details
  corporateCode: z.string().optional(),
  joiningDate: z.string().optional(),
  confirmationDate: z.string().optional(),
  hrName: z.string().optional(),
  hrDesignation: z.string().optional(),
  hrEmail: z.string().optional(),
  hrMobile: z.string().optional(),
  
  basicSalary: z.string().optional(),
  houseRentAllowance: z.string().optional(),
  festivalBonus: z.string().optional(),
  providentFundDeduction: z.string().optional(),
  netTakeHomePay: z.string().optional(),
  existingLoanBank: z.string().optional(),
  existingLoanEmi: z.string().optional(),
  existingCreditCardOutstanding: z.string().optional(),
  
  businessName: z.string().min(1, { message: isBn ? "ব্যবসার নাম দিন" : "Enter business name" }).optional(),
  brandName: z.string().optional(),
  shopAddress: z.string().min(1, { message: isBn ? "ঠিকানা দিন" : "Enter address" }).optional(),
  tradeLicense: z.string().min(1, { message: isBn ? "ট্রেড লাইসেন্স দিন" : "Enter trade license" }).optional(),
  tradeLicenseIssueDate: z.string().optional(),
  vatBinNumber: z.string().optional(),
  rjscNumber: z.string().optional(),
  factoryAddress: z.string().optional(),
  showroomCount: z.string().optional(),
  totalEmployees: z.string().optional(),
  yearsInProfit: z.string().optional(),
  avgMonthlySales: z.string().optional(),
  seasonalSales: z.string().optional(),
  cogs: z.string().optional(),
  netProfitMargin: z.string().optional(),
  accountsReceivable: z.string().optional(),
  accountsPayable: z.string().optional(),
  currentStockValue: z.string().optional(),
  loanPurposeDetails: z.string().optional(),
  mainCurrentAccount: z.string().optional(),
  ccOdLimit: z.string().optional(),
  otherActiveLoans: z.string().optional(),
  
  equityPercentage: z.string().optional(),
  applicantRole: z.string().optional(),
  productType: z.string().optional(),
  rawMaterialSource: z.string().optional(),
  salesChannel: z.string().optional(),
  govtScheme: z.string().optional(),
  
  workingCountry: z.string().min(1, { message: isBn ? "দেশের নাম দিন" : "Enter working country" }).optional(),
  visaType: z.string().min(1, { message: isBn ? "ভিসার ধরন দিন" : "Enter visa type" }).optional(),
  passportNumber: z.string().min(1, { message: isBn ? "পাসপোর্ট নাম্বার দিন" : "Enter passport NO" }).optional(),
  passportIssueDate: z.string().optional(),
  passportExpiryDate: z.string().optional(),
  iqamaNumber: z.string().optional(),
  foreignAddress: z.string().optional(),
  foreignMobile: z.string().optional(),
  foreignWhatsapp: z.string().optional(),
  foreignCompanyName: z.string().optional(),
  foreignCompanyContact: z.string().optional(),
  workerCategory: z.string().optional(),
  supervisorNameContact: z.string().optional(),
  avgMonthlyRemittance: z.string().optional(),
  remittanceChannel: z.string().optional(),
  receiverBankAccount: z.string().optional(),
  coApplicantName: z.string().optional(),
  coApplicantRelation: z.string().optional(),
  coApplicantProfession: z.string().optional(),
  coApplicantIncome: z.string().optional(),
  coApplicantNid: z.string().optional(),
  coApplicantCurrentAddress: z.string().optional(),
  coApplicantPermanentAddress: z.string().optional(),
  
  institutionName: z.string().min(1, { message: isBn ? "প্রতিষ্ঠানের নাম দিন" : "Enter institution name" }).optional(),
  studentId: z.string().min(1, { message: isBn ? "স্টুডেন্ট আইডি দিন" : "Enter student ID" }).optional(),
  guardianIncome: z.string().min(1, { message: isBn ? "আয় দিন" : "Enter income" }).optional(),
  latestCertificate: z.string().min(1, { message: isBn ? "সার্টিফিকেট নির্বাচন করুন" : "Select certificate" }).optional(),
  runningStudent: z.string().min(1, { message: isBn ? "বর্তমান পড়াশোনার বিবরণ দিন" : "Enter current study details" }).optional(),
  institutionAddress: z.string().min(1, { message: isBn ? "প্রতিষ্ঠানের ঠিকানা দিন" : "Enter institution address" }).optional(),
  
  sscRoll: z.string().optional(),
  sscReg: z.string().optional(),
  sscBoard: z.string().optional(),
  sscGpa: z.string().optional(),
  sscYear: z.string().optional(),
  sscInstitution: z.string().optional(),

  hscRoll: z.string().optional(),
  hscReg: z.string().optional(),
  hscBoard: z.string().optional(),
  hscGpa: z.string().optional(),
  hscYear: z.string().optional(),
  hscInstitution: z.string().optional(),

  gradRoll: z.string().optional(),
  gradReg: z.string().optional(),
  gradBoard: z.string().optional(),
  gradCgpa: z.string().optional(),
  gradYear: z.string().optional(),
  gradInstitution: z.string().optional(),

  targetUniversity: z.string().optional(),
  targetDepartment: z.string().optional(),
  courseRanking: z.string().optional(),
  creditHours: z.string().optional(),
  tuitionFee: z.string().optional(),
  accommodationCost: z.string().optional(),
  healthInsurance: z.string().optional(),
  otherFees: z.string().optional(),

  sponsorName: z.string().optional(),
  sponsorRelation: z.string().optional(),
  sponsorIncomeSource: z.string().optional(),
  sponsorJobDetails: z.string().optional(),
  sponsorTaxableIncome: z.string().optional(),
  sponsorNetWorth: z.string().optional(),
  
  professionName: z.string().min(1, { message: isBn ? "পেশা দিন" : "Enter profession" }).optional(),
  patientName: z.string().optional(),
  patientRelation: z.string().optional(),
  patientNid: z.string().optional(),
  patientCondition: z.string().optional(),
  
  hospitalName: z.string().optional(),
  referringDoctor: z.string().optional(),
  doctorBmdc: z.string().optional(),
  hospitalDepartment: z.string().optional(),
  treatmentType: z.string().optional(),
  
  estimatedCost: z.string().optional(),
  applicantContribution: z.string().optional(),
  insuranceCoverage: z.string().optional(),
  insuranceAmount: z.string().optional(),
  shortfallAmount: z.string().optional(),
  hrContactNumber: z.string().optional(),
  
  workType: z.string().min(1, { message: isBn ? "কাজের ধরন নির্বাচন করুন" : "Select work type" }).optional(),
  workDescription: z.string().min(1, { message: isBn ? "কাজের বিবরণ দিন" : "Enter work description" }).optional(),
  workAddress: z.string().min(1, { message: isBn ? "কাজের স্থান বা ঠিকানা দিন" : "Enter work location/address" }).optional(),

  // Step 5
  bankName: z.string().min(2, { message: isBn ? "ব্যাংকের নাম দিন" : "Enter bank name" }),
  accountName: z.string().min(2, { message: isBn ? "একাউন্টের নাম দিন" : "Enter account name" }),
  accountNumber: z.string().min(5, { message: isBn ? "সঠিক একাউন্ট নম্বর দিন" : "Enter valid account number" }),
  routingNumber: z.string().optional(),
  mobileBanking: z.string().regex(/^(01)[3-9][0-9]{8}$/, { message: isBn ? "সঠিক নাম্বার দিন (১১ ডিজিট)" : "Enter valid number" }).optional().or(z.literal('')),
  nomineeName: z.string().min(3, { message: isBn ? "নমিনির নাম দিন" : "Enter nominee name" }),
  nomineeRelation: z.string().min(2, { message: isBn ? "সম্পর্ক উল্লেখ করুন" : "Enter relationship" }),
  nomineeMobile: z.string().regex(/^(01)[3-9][0-9]{8}$/, { message: isBn ? "সঠিক মোবাইল নাম্বার দিন" : "Enter valid mobile number" }),
  nomineeNid: z.string().min(10, { message: isBn ? "সঠিক NID নাম্বার দিন (অন্তত ১০ ডিজিট)" : "Enter valid NID (min 10 digits)" }),
  
  // Guarantors (for Personal Loan)
  g1Name: z.string().optional(),
  g1Relation: z.string().optional(),
  g1Nid: z.string().optional(),
  g1Mobile: z.string().optional(),
  g1Address: z.string().optional(),
  g1Profession: z.string().optional(),
  
  g2Name: z.string().optional(),
  g2Designation: z.string().optional(),
  g2OfficialId: z.string().optional(),
  g2Email: z.string().optional(),
  g2Mobile: z.string().optional(),
});

export type LoanFormData = z.infer<ReturnType<typeof getLoanSchema>>;
export type AddressFormData = z.infer<ReturnType<typeof addressSchema>>;
