import { ArrowDownToLine, ArrowUpFromLine, Wallet, CreditCard } from 'lucide-react';
import { Link } from 'react-router-dom';
import { formatCurrency } from '../../lib/translation';
import type { Transaction } from '../../types/database';

type Props={isBn:boolean;transactions:Transaction[]};
export function RecentActivity({isBn,transactions}:Props){
const recent=transactions.slice(0,4);
const status=(s:string)=>s==='completed'?(isBn?'সম্পন্ন':'Completed'):s==='pending'?(isBn?'অপেক্ষমাণ':'Pending'):s==='failed'?(isBn?'ব্যর্থ':'Failed'):s;
const label=(t:string)=>t==='deposit'?(isBn?'সঞ্চয়/ডিপোজিট':'Deposit'):t==='emi_payment'?(isBn?'কিস্তি পরিশোধ':'EMI payment'):t==='disbursement'?(isBn?'ঋণ বিতরণ':'Loan disbursement'):(isBn?'উত্তোলন':'Withdrawal');
const meta=(t:Transaction['type'])=>t==='deposit'?{sign:'+',amountClass:'text-emerald-600 dark:text-emerald-400',iconClass:'bg-emerald-50 text-emerald-600 dark:bg-emerald-950/40 dark:text-emerald-400'}:t==='emi_payment'?{sign:'−',amountClass:'text-sky-600 dark:text-sky-400',iconClass:'bg-sky-50 text-sky-600 dark:bg-sky-950/40 dark:text-sky-400'}:t==='disbursement'?{sign:'+',amountClass:'text-violet-600 dark:text-violet-400',iconClass:'bg-violet-50 text-violet-600 dark:bg-violet-950/40 dark:text-violet-400'}:{sign:'−',amountClass:'text-rose-600 dark:text-rose-400',iconClass:'bg-rose-50 text-rose-600 dark:bg-rose-950/40 dark:text-rose-400'};
return <section><div className="flex justify-between items-end mb-3"><div><p className="text-[10px] uppercase tracking-wider font-black text-slate-400">{isBn?'লেনদেন':'Activity'}</p><h2 className="text-lg font-black mt-1">{isBn?'সাম্প্রতিক কার্যক্রম':'Recent activity'}</h2></div><Link to="/transactions" className="text-xs font-black text-sky-600 dark:text-sky-400">{isBn?'সব দেখুন':'View all'}</Link></div><div className="home-activity-card rounded-2xl overflow-hidden">{recent.length?recent.map((tx,i)=><div key={tx.id} className={`p-4 flex items-center gap-3 ${i<recent.length-1?'border-b border-slate-100 dark:border-slate-800':''}`}><div className={`w-10 h-10 rounded-xl flex items-center justify-center ${meta(tx.type).iconClass}`}>{tx.type==='deposit'?<ArrowDownToLine size={17}/>:tx.type==='emi_payment'?<CreditCard size={17}/>:tx.type==='disbursement'?<ArrowUpFromLine size={17}/>:<Wallet size={17}/>}</div><div className="flex-1 min-w-0"><p className="text-xs font-black">{label(tx.type)}</p><p className="text-[10px] text-slate-400 mt-1">{new Date(tx.created_at).toLocaleDateString(isBn?'bn-BD':'en-GB')} • {status(tx.status)}</p></div><div className="text-right"><p className={`text-xs font-black ${meta(tx.type).amountClass}`}>{meta(tx.type).sign} {formatCurrency(tx.amount,isBn)}</p><p className={`text-[9px] font-bold mt-1 ${tx.status==='completed'?'text-emerald-600 dark:text-emerald-400':tx.status==='failed'?'text-rose-600 dark:text-rose-400':'text-amber-600 dark:text-amber-400'}`}>{status(tx.status)}</p></div></div>):<div className="p-8 text-center text-xs font-bold text-slate-400">{isBn?'সাম্প্রতিক কোনো কার্যক্রম নেই':'No recent activity'}</div>}</div></section>;
}