import { ChevronRight, Star } from 'lucide-react';
import { Link } from 'react-router-dom';
import { formatCurrency, convertDigits } from '../../lib/translation';
import type { SuccessStory } from '../../types/database';

type Props={isBn:boolean;stories:SuccessStory[];storyReactions:Record<string,{like:number;love:number;wow:number}>;onReact:(story:SuccessStory,type:'like'|'love'|'wow')=>void};

export function SuccessStories({isBn,stories,storyReactions,onReact}:Props){
if(!stories.length)return null;
return <section>
<div className="flex items-end justify-between mb-3"><div><p className="text-[10px] uppercase tracking-wider font-black text-slate-500">{isBn?'সদস্যদের অভিজ্ঞতা':'SUCCESS STORIES'}</p><h2 className="text-xl font-extrabold mt-1 text-slate-900 dark:text-white">{isBn?'সাফল্যের গল্প':'Success Stories'}</h2></div><Link to="/success-stories" className="inline-flex items-center gap-1 text-xs font-bold text-blue-700 dark:text-sky-300">{isBn?'সব দেখুন':'View all'} <ChevronRight size={16}/></Link></div>
<div className="-mx-4 px-4 overflow-x-auto hide-scrollbar snap-x snap-mandatory"><div className="flex gap-3 w-max">
{stories.slice(0,10).map(story=><article key={story.id} className="home-success-story w-[calc(100vw-2rem)] max-w-[620px] min-w-[calc(100vw-2rem)] sm:min-w-[min(620px,calc(100vw-3rem))] shrink-0 snap-start rounded-[22px] p-4 sm:p-5 text-white relative overflow-hidden">
<div className="home-story-dots absolute right-5 bottom-4 pointer-events-none" aria-hidden="true"/>
<div className="relative z-10 flex items-center justify-between gap-3"><div className="flex items-center gap-2.5 min-w-0"><Star size={25} className="text-white shrink-0"/><div className="min-w-0"><p className="text-sm sm:text-base font-extrabold">{isBn?'সাফল্যের গল্প':'Member success story'}</p><p className="text-[10px] sm:text-xs text-white/75 mt-0.5">{isBn?'আমাদের সদস্যদের সাফল্যের পথ':'Stories of our members’ success'}</p></div></div>{story.is_verified&&<span className="home-story-verified text-[9px] font-extrabold rounded-full px-2.5 py-1 shrink-0">{isBn?'যাচাইকৃত':'Verified'}</span>}</div>
<div className="relative z-10 mt-4 flex items-center gap-3 sm:gap-4"><img src={story.avatar_url||`https://ui-avatars.com/api/?name=${encodeURIComponent(story.name)}&background=0ea5e9&color=fff&bold=true`} alt="" className="w-[68px] h-[68px] sm:w-[78px] sm:h-[78px] rounded-full object-cover border-2 border-white/80 bg-white/20 shrink-0"/><div className="min-w-0 flex-1"><p className="text-sm sm:text-base font-bold leading-snug line-clamp-3">{isBn?'প্রভাতী লোনের সদস্যের অভিজ্ঞতা':'A member’s journey with Provati Loan'}</p><p className="text-xs sm:text-sm font-extrabold mt-2 truncate">{story.name}</p><p className="text-[10px] sm:text-xs text-white/75 mt-0.5 truncate">{story.loan_type||story.profession||(isBn?'সদস্য':'Member')} {story.amount?` • ${formatCurrency(story.amount,isBn)}`:''}</p></div><span className="hidden sm:block text-5xl leading-none font-black text-white/20 self-end">”</span></div>
<div className="relative z-10 mt-3 pt-3 border-t border-white/20 flex items-center justify-between gap-2"><div className="flex text-amber-300 shrink-0">{Array.from({length:Math.min(story.rating||5,5)}).map((_,i)=><Star key={i} size={12} fill="currentColor"/>)}</div><div className="flex items-center gap-1.5">{(['like','love','wow'] as const).map(type=>{const base=type==='like'?Number(story.like_count||0):type==='love'?Number(story.love_count||0):Number(story.wow_count||0);const count=storyReactions[story.id]?.[type]??base;return <button key={type} type="button" onClick={()=>onReact(story,type)} className="px-2 py-1 rounded-full bg-white/15 border border-white/25 text-[10px] text-white active:scale-95 transition">{type==='like'?'👍':type==='love'?'❤️':'😮'} {convertDigits(count,isBn)}</button>})}</div></div>
</article>)}</div></div></section>;
}